#Ultima actualizacion 26 mayo 2022

#CORRIDA = range(0,3)
CORRIDA = range(10)
#PARTICULA = ["gamma"]
PARTICULA = ["e-", "gamma", "mu-"]
#container: "docker://manu33/wcsim:1.2"

rule all:
   input:
      expand('../../data/1_MAC/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.mac', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/1_MAC/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.mac', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/1_MAC/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.mac', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/3_NPZ_event_dump/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/3_NPZ_event_dump/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/3_NPZ_event_dump/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/3_NPZ_event_dump/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/4_Imagen_NPZ/VaryE/e-/IMAGES_wcs_MCA_e-__{l_corrida}_500_MeV.npy', l_corrida=CORRIDA),
      expand('../../data/3_NPZ_event_dump/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/4_Imagen_NPZ/VaryE/gamma/IMAGES_wcs_MCA_gamma__{l_corrida}_500_MeV.npy', l_corrida=CORRIDA),
      expand('../../data/3_NPZ_event_dump/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/4_Imagen_NPZ/VaryE/mu-/IMAGES_wcs_MCA_mu-__{l_corrida}_500_MeV.npy', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/5_NPZ_event_dump_barrel/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/5_NPZ_event_dump_barrel/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA),
      expand('../../data/2_ROOT/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
      expand('../../data/5_NPZ_event_dump_barrel/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA)



# -----------------------------------------------------------------------------------------------------
# MAC_to_ROOT
# -----------------------------------------------------------------------------------------------------


# Con respecto a VaryE
rule MAC_to_ROOT_e:
   input:
      '../../data/1_MAC/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.mac'
   output:
      '../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root'
   params:
      ruta = '../../data/1_MAC/VaryE/e-/',
      i = '/home/shared-folder/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.mac',
      m = 'wcs_MCA_e-__{l_corrida}_500_MeV.mac',
      r = 'wcs_MCA_e-__{l_corrida}_500_MeV.root'

   group: "mygroup"

   shell:
    """
       sudo docker exec -it WCSim_e bash -c "cd /home/neutrino/software; source run.sh; cd /home/neutrino/software/WCSim_build; ./WCSim /home/neutrino/in_out_demos/{params.m}; mv /home/neutrino/software/WCSim_build/{params.r} /home/neutrino/in_out_demos/"
       mv {params.ruta}{params.r}  {output}
       sudo chmod 666 {output}
    """

# Con respecto a VaryE
rule MAC_to_ROOT_mu:
   input:
      '../../data/1_MAC/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.mac'
   output:
      '../../data/2_ROOT/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.root'
   params:
      ruta = '../../data/1_MAC/VaryE/mu-/',
      i = '/home/shared-folder/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.mac',
      m = 'wcs_MCA_mu-__{l_corrida}_500_MeV.mac',
      r = 'wcs_MCA_mu-__{l_corrida}_500_MeV.root'

   group: "mygroup"

   shell:
    """
       sudo docker exec -it WCSim_m bash -c "cd /home/neutrino/software; source run.sh; cd /home/neutrino/software/WCSim_build; ./WCSim /home/neutrino/in_out_demos/{params.m}; mv /home/neutrino/software/WCSim_build/{params.r} /home/neutrino/in_out_demos/"
       mv {params.ruta}{params.r}  {output}
       sudo chmod 666 {output}
    """



# Con respecto a VaryE
rule MAC_to_ROOT_gamma:
   input:
      '../../data/1_MAC/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.mac'
   output:
      '../../data/2_ROOT/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.root'
   params:
      ruta = '../../data/1_MAC/VaryE/gamma/',
      i = '/home/shared-folder/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.mac',
      m = 'wcs_MCA_gamma__{l_corrida}_500_MeV.mac',
      r = 'wcs_MCA_gamma__{l_corrida}_500_MeV.root'

   group: "mygroup"
   shell:
    """
       sudo docker exec -it WCSim_g bash -c "cd /home/neutrino/software; source run.sh; cd /home/neutrino/software/WCSim_build; ./WCSim /home/neutrino/in_out_demos/{params.m}; mv /home/neutrino/software/WCSim_build/{params.r} /home/neutrino/in_out_demos/"
       mv {params.ruta}{params.r}  {output}
       sudo chmod 666 {output}
    """

# -----------------------------------------------------------------------------------------------------
# ROOT_to_event_dump
# -----------------------------------------------------------------------------------------------------

# Con respecto a VaryE -  root to NPZ ROOT_to_event_dump
rule ROOT_to_event_dump_e:
   input:
      '../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root'
   output:
      '../../data/3_NPZ_event_dump/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz'
   params:
      ruta = '../../data/2_ROOT/VaryE/e-/',
      m = 'wcs_MCA_e-__{l_corrida}_500_MeV.root',
      r = 'wcs_MCA_e-__{l_corrida}_500_MeV.npz'
   group: "mygroup"
   shell:
    """
       sudo docker exec -it WCSim_2e bash -c "cd /home/neutrino/software; source run.sh; cd /home/WatChMal/DataTools; time python3 event_dump.py /home/neutrino/in_out_demos/{params.m} /home/neutrino/in_out_demos"
       mv {params.ruta}{params.r}  {output}
       sudo chmod 666 {output}
    """

# Con respecto a VaryE -  root to NPZ ROOT_to_event_dump
rule ROOT_to_event_dump_gamma:
   input:
      '../../data/2_ROOT/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.root'
   output:
      '../../data/3_NPZ_event_dump/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.npz'
   params:
      ruta = '../../data/2_ROOT/VaryE/gamma/',
      m = 'wcs_MCA_gamma__{l_corrida}_500_MeV.root',
      r = 'wcs_MCA_gamma__{l_corrida}_500_MeV.npz'
   group: "mygroup"
   shell:
    """
       sudo docker exec -it WCSim_2g bash -c "cd /home/neutrino/software; source run.sh; cd /home/WatChMal/DataTools; time python3 event_dump.py /home/neutrino/in_out_demos/{params.m} /home/neutrino/in_out_demos"
       mv {params.ruta}{params.r} {output}
       sudo chmod 666 {output}
    """

# Con respecto a VaryE -  root to NPZ ROOT_to_event_dump
rule ROOT_to_event_dump_mu:
   input:
      '../../data/2_ROOT/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.root'
   output:
      '../../data/3_NPZ_event_dump/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.npz'
   params:
      ruta = '../../data/2_ROOT/VaryE/mu-/',
      m = 'wcs_MCA_mu-__{l_corrida}_500_MeV.root',
      r = 'wcs_MCA_mu-__{l_corrida}_500_MeV.npz'
   group: "mygroup"
   shell:
    """
       sudo docker exec -it WCSim_2m bash -c "cd /home/neutrino/software; source run.sh; cd /home/WatChMal/DataTools; time python3 event_dump.py /home/neutrino/in_out_demos/{params.m} /home/neutrino/in_out_demos"
       mv {params.ruta}{params.r} {output}
       sudo chmod 666 {output}
    """

# -----------------------------------------------------------------------------------------------------
# NPZ_to_image
# -----------------------------------------------------------------------------------------------------

# Con respecto a VaryE -  NPZ (Event Dump) to IMAGE
rule NPZ_to_image_e:
   input:
      '../../data/3_NPZ_event_dump/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz'
   output:
      '../../data/4_Imagen_NPZ/VaryE/e-/IMAGES_wcs_MCA_e-__{l_corrida}_500_MeV.npy'
   params:
      ruta = '../../data/3_NPZ_event_dump/VaryE/e-/',
      m = 'wcs_MCA_e-__{l_corrida}_500_MeV.npz',
      r = 'IMAGES_wcs_MCA_e-__{l_corrida}_500_MeV.npy'
   group: "mygroup"
   shell:
    """
       time python3 ../../scripts/python/npz_to_image.py -m ../../data/Geometries/IWCD_geometry_mPMT.npy -f {input}
       mv {params.r}  {output}
       sudo chmod 666 {output}
    """

# Con respecto a VaryE -  NPZ (Event Dump) to IMAGE
rule NPZ_to_image_gamma:
   input:
      '../../data/3_NPZ_event_dump/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.npz'
   output:
      '../../data/4_Imagen_NPZ/VaryE/gamma/IMAGES_wcs_MCA_gamma__{l_corrida}_500_MeV.npy'
   params:
      ruta = '../../data/3_NPZ_event_dump/VaryE/gamma/',
      m = 'wcs_MCA_gamma__{l_corrida}_500_MeV.npz',
      r = 'IMAGES_wcs_MCA_gamma__{l_corrida}_500_MeV.npy'
   group: "mygroup"
   shell:
    """
       time python3 ../../scripts/python/npz_to_image.py -m ../../data/Geometries/IWCD_geometry_mPMT.npy -f {input}
       mv {params.r}  {output}
       sudo chmod 666 {output}
    """

# Con respecto a VaryE -  NPZ (Event Dump) to IMAGE
rule NPZ_to_image_m:
   input:
      '../../data/3_NPZ_event_dump/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.npz'
   output:
      '../../data/4_Imagen_NPZ/VaryE/mu-/IMAGES_wcs_MCA_mu-__{l_corrida}_500_MeV.npy'
   params:
      ruta = '../../data/3_NPZ_event_dump/VaryE/mu-/',
      m = 'wcs_MCA_mu-__{l_corrida}_500_MeV.npz',
      r = 'IMAGES_wcs_MCA_mu-__{l_corrida}_500_MeV.npy'
   group: "mygroup"
   shell:
    """
       time python3 ../../scripts/python/npz_to_image.py -m ../../data/Geometries/IWCD_geometry_mPMT.npy -f {input}
       mv {params.r}  {output}
       sudo chmod 666 {output}
    """


# -----------------------------------------------------------------------------------------------------
# ROOT to NPZ event_dump_barrel
# -----------------------------------------------------------------------------------------------------

# Con respecto a VaryE -  root to NPZ ROOT_to_event_dump
rule ROOT_to_event_dump_barrel_e:
   input:
      '../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root'
   output:
      '../../data/5_NPZ_event_dump_barrel/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz'
   params:
      ruta = '../../data/2_ROOT/VaryE/e-/',
      m = 'wcs_MCA_e-__{l_corrida}_500_MeV.root',
      r = 'wcs_MCA_e-__{l_corrida}_500_MeV.npz'
   group: "mygroup"
   shell:
    """
       sudo docker exec -it WCSim_4e bash -c "cd /home/neutrino/software; source run.sh; cd /home/WatChMal/DataTools; time python3 event_dump_barrel.py /home/neutrino/in_out_demos/{params.m} /home/neutrino/in_out_demos"
       mv {params.ruta}{params.r}  {output}
       sudo chmod 666 {output}
    """


rule ROOT_to_event_dump_barrel_gamma:
   input:
      '../../data/2_ROOT/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.root'
   output:
      '../../data/5_NPZ_event_dump_barrel/VaryE/gamma/wcs_MCA_gamma__{l_corrida}_500_MeV.npz'
   params:
      ruta = '../../data/2_ROOT/VaryE/gamma/',
      m = 'wcs_MCA_gamma__{l_corrida}_500_MeV.root',
      r = 'wcs_MCA_gamma__{l_corrida}_500_MeV.npz'
   group: "mygroup"
   shell:
    """
       sudo docker exec -it WCSim_4g bash -c "cd /home/neutrino/software; source run.sh; cd /home/WatChMal/DataTools; time python3 event_dump_barrel.py /home/neutrino/in_out_demos/{params.m} /home/neutrino/in_out_demos"
       mv {params.ruta}{params.r}  {output}
       sudo chmod 666 {output}
    """


rule ROOT_to_event_dump_barrel_mu:
   input:
      '../../data/2_ROOT/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.root'
   output:
      '../../data/5_NPZ_event_dump_barrel/VaryE/mu-/wcs_MCA_mu-__{l_corrida}_500_MeV.npz'
   params:
      ruta = '../../data/2_ROOT/VaryE/mu-/',
      m = 'wcs_MCA_mu-__{l_corrida}_500_MeV.root',
      r = 'wcs_MCA_mu-__{l_corrida}_500_MeV.npz'
   group: "mygroup"
   shell:
    """
       sudo docker exec -it WCSim_4m bash -c "cd /home/neutrino/software; source run.sh; cd /home/WatChMal/DataTools; time python3 event_dump_barrel.py /home/neutrino/in_out_demos/{params.m} /home/neutrino/in_out_demos"
       mv {params.ruta}{params.r}  {output}
       sudo chmod 666 {output}
    """
